# Generated by Django 4.2 on 2025-05-03 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
    ]
