# Generated by Django 4.2 on 2025-05-04 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0004_enrollment_completed_lessons'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
